services:
  postgres:
    container_name: nextjs-postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=h3ll0
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=nextjsdb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
